theme: jekyll-theme-minimal
title: ğŸ“
description: |
  ğŸ  Paris, France
  <br/>
  <a href="tel:+33 7 55 91 36 26">ğŸ“±ğŸ‡«ğŸ‡· +33 7 55 91 36 26</a>
  <br/>
  <a href="mailto:bocoumidi@gmail.com">ğŸ“§ bocoumidi@gmail.com</a>
  <br/>
  <a href="https://github.com/bocoumidi">ğŸ‘¨ğŸ¾â€ğŸ’» Github</a>
  <br/>
  <a href="https://www.linkedin.com/in/idybocoum/">ğŸ–‡ï¸ LinkedIn</a>
  <br/>
